
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aakash
 */
public class Main extends javax.swing.JFrame {
Graphics2D g2d;
int x1 = 100, y1 = 100, x2 = 150, y2 = 150, x3, y3, x4, y4, width = 100;
Rectangle2D rect1 = new Rectangle2D.Float(x1, y1, width, width);
Rectangle2D rect2 = new Rectangle2D.Float(x2, y2, width, width);
Line2D line1 = new Line2D.Float(x1, y1, x2, y2);
Line2D line2 = new Line2D.Float(x3, y1, x4, y2);
Line2D line3 = new Line2D.Float(x1, y3, x2, y4);
Line2D line4 = new Line2D.Float(x3, y3, x4, y4);
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

    }
    public void paint(Graphics g){
        g2d = (Graphics2D)g;
        super.paintComponents(g);
        line1 = new Line2D.Float(x1, y1, x2, y2);
        line2 = new Line2D.Float(x3, y1, x4, y2);
        line3 = new Line2D.Float(x1, y3, x2, y4);
        line4 = new Line2D.Float(x3, y3, x4, y4);
        rect1 = new Rectangle2D.Float(x1, y1, width, width);
        rect2 = new Rectangle2D.Float(x2, y2, width, width);
        g2d.draw(rect1);
        g2d.draw(rect2);
        g2d.draw(line1);
        g2d.draw(line2);
        g2d.draw(line3);
        g2d.draw(line4);
        g2d.drawString(""+x1+","+y1, x1, y1);
        g2d.drawString(""+x3+","+y1, x3, y1);
        g2d.drawString(""+x1+","+y3, x1, y3);
        g2d.drawString(""+x3+","+y3, x3, y3);
        g2d.drawString(""+x2+","+y2, x2, y2);
        g2d.drawString(""+x4+","+y2, x4, y2);
        g2d.drawString(""+x2+","+y4, x2, y4);
        g2d.drawString(""+x4+","+y4, x4, y4);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mathemtically Cube Rotating Program");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        x3 = x1+width;
        y3 = y1+width;
        x4 = x2+100;
        y4 = y2+100;
        repaint();
        if(evt.getKeyCode()==39){
            x2 = x2+1;
            x4 = x4+1;
            repaint();
    }
     else if(evt.getKeyCode()==37){
            x2 = x2-1;
            x4 = x4-1;
            repaint();
    }
    else if(evt.getKeyCode()==40){
            y2 = y2+1;
            y2 = y2+1;
            repaint();
    }
    else if(evt.getKeyCode()==38){
            y2 = y2-1;
            y2 = y2-1;
            repaint();
    }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
