
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GameRun.java
 *
 * Created on Mar 27, 2014, 10:10:30 AM
 */

/**
 *
 * @author Aakash
 */
public class GameRun extends javax.swing.JFrame {
Graphics g;
Graphics2D g2d;
BufferedImage launcher, fire, enemy, enemy_down;
int fire_y = 440, fire_x = 590, enemy_x=1210;
Timer tim1, tim2;
    /** Creates new form GameRun */
    public GameRun() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        panel1 = new java.awt.Panel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Load Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        panel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panel1KeyPressed(evt);
            }
        });
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel1MouseClicked(evt);
            }
        });
        panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel1MouseMoved(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panel1Layout = new org.jdesktop.layout.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1310, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 594, Short.MAX_VALUE)
        );

        jToolBar1.add(panel1);

        jButton2.setText("Start");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Press SPACE to launch the fire. Remember! you will get only one chance to eleiminate the star.");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addContainerGap(724, Short.MAX_VALUE))
            .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1332, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1312, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
g = panel1.getGraphics();
g2d = (Graphics2D)g;
jButton1.setEnabled(false);
try{
    launcher = ImageIO.read(new File("src/Launcher.png"));
    fire = ImageIO.read(new File("src/Fire.png"));
    enemy = ImageIO.read(new File("src/Enemy.png"));
    enemy_down = ImageIO.read(new File("src/enemy_down.png"));
}
catch(Exception ec) {
    }
g2d.drawImage(launcher, null, 580, 500);
g2d.drawImage(fire, null, 590, 440);
g2d.drawImage(enemy, null, 1210, 70);
jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void panel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseMoved

    }//GEN-LAST:event_panel1MouseMoved

    private void panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseClicked

    }//GEN-LAST:event_panel1MouseClicked

    private void panel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panel1KeyPressed
int key = evt.getKeyCode();
if(key == KeyEvent.VK_SPACE) {
    tim1 = new Timer(10, new ActionListener() {
public void actionPerformed(ActionEvent e) {
  fire_y = fire_y-30;
  g2d.clearRect(fire_x, fire_y+30, fire.getWidth(), fire.getHeight());
  g2d.drawImage(fire, null, fire_x, fire_y);
if(fire_x >= enemy_x) {
    if((fire_x+fire.getWidth()) <= (enemy_x+enemy.getWidth())) {
        if(fire_y <= (70+enemy.getHeight())) {
            if(fire_y-fire.getHeight() >= 70) {
                tim1.stop();
                tim2.stop();
                g2d.clearRect(0, 0, 10000, 500);
                g2d.drawImage(enemy_down, null, enemy_x+10, 60);
                JOptionPane.showMessageDialog(null, "Congratulations!! you have won.");
                System.exit(0);
            }
        }
    }
}
}
});
tim1.start();
}
if(key == KeyEvent.VK_LEFT) {
    fire_x = fire_x-20;
    g2d.clearRect(0, 440, 5000, 5000);
   g2d.drawImage(launcher, null, fire_x, 500);
   g2d.drawImage(fire, null, fire_x+10, 440);
}
if(key == KeyEvent.VK_RIGHT) {
    fire_x = fire_x+20;
    g2d.clearRect(0, 440, 5000, 5000);
   g2d.drawImage(launcher, null, fire_x, 500);
   g2d.drawImage(fire, null, fire_x+10, 440);
}
    }//GEN-LAST:event_panel1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
tim2 = new Timer(10, new ActionListener() {
   public void actionPerformed(ActionEvent e) {
enemy_x = enemy_x-5;
  g2d.clearRect(enemy_x+50, 70, enemy.getWidth(), enemy.getHeight());
  g2d.drawImage(enemy, null, enemy_x, 70);
   }
});
tim2.start();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
 try{
     UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
 }
 catch(Exception exc) {
     
 }
                new GameRun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

}
